name: Continuous Integration and Continuous Delivery ⚙🚀

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Check and Build 👷‍♂️
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x, "lts/*"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Use NodeJS ${{ matrix.node }} 📦
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # v2.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install and Check 👨‍💻
        run: |
          yarn install --frozen-lockfile --check-files
          yarn build

      - name: Update Browserlist 🕵️‍♂️
        run: npx browserslist@latest --update-db

      - name: Build 🔧
        run: yarn build

  deploy:
    name: Deploy to production ✨🚀
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["lts/*"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Use NodeJS ${{ matrix.node }} 📦
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # v2.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install and Build 🔧
        run: |
          yarn install --frozen-lockfile --check-files
          npx browserslist@latest --update-db
          yarn build:webpack

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: soccerman.latipun.dev
